### ISSUE TITLE
Failed Running the example

### ISSUE THREAD

**Issue by phuwanat** [xqwen/integrative#1]
Hello,

I have tried runnign the example dataset using enloc. Everything appears fine until the last line:

```
Start co-localization analysis
Find GWAS QTLs ...
Read in 1700 loci, 6127680 locus-SNP pairs ...
Initializing ...
Starting EM ...
  Iter          loglik          Intercept
   1         -1691.244           -8.537
   2          1754.546           -9.207
   3          1998.997           -9.598
   4          2053.407           -9.840
   5          2069.462           -9.990
   6          2074.747          -10.084
   7          2076.574          -10.141
   8          2077.221          -10.176
   9          2077.452          -10.198
  10          2077.535          -10.211


    Total Loci: 1700   Rejections: 72
Summarize QTL PIPs ..
Prepare for co-localizaiton analysis ...
Compute priors ...
Perform fine-mapping of GWAS ...
Compute regional col-localization probabilities ...
cat: /home/phuwanat/sw/enloc/workspace/HDL_blood/rcp_out/*.rcp: No such file or directory
```

Thanks,
Phuwanat

**Comment by xqwen** [comment]
I would check the enrichment analysis part, especially the eQTL data, to make sure the multiple imputation procedure is performed properly. In particular, look for the output file with suffix ".enrich.est" and examine its content.

Best,
William

**Comment by phuwanat** [comment]
Actually, the rcp_out/*.rcp are present properly in the directory but I don't know why the error was still present. 
These are the contents from .enrich.est files; that seems fine to me.
```
  -10.376    -10.448    -10.305
    4.714      3.021      6.408
```

Did you successfully re-run the example pipeline?

**Comment by xqwen** [comment]
I just repeated the example from the scratch and see no problem. 

Can you just simply issue the following command from the ```workspace``` directory?
``` cat HDL_blood/rcp_out/*.rcp | sort -nrk4 > HDL_blood/HDL.enloc.rst```
and check the resulting ```HDL.enloc.rst```?

If all the rcp files are already in the directory, it indicates all the key analyses are completed. There might be a problem that you shell interprets the wildcard ```*``` from the enloc script.

William

**Comment by xqwen** [comment]
Seems related to [this resolved issue](https://github.com/xqwen/integrative/issues/5). Closing it for now.
