### ISSUE TITLE
Problem running the examples in tutorial

### ISSUE THREAD

**Issue by ruthchia** [xqwen/integrative#3]
Hi, I tried running your example and was returned with an error "zcat: can't stat: ... : No such file or directory
A snapshot of the error is attached.
I have everything setup according to your directory tree. Can you please advise what the problem could be?
Thanks
Ruth

![error_enloc](https://user-images.githubusercontent.com/20730081/27595078-a277bb08-5b29-11e7-9603-1c5b535f941e.png)

**Comment by xqwen** [comment]
All the *.gz files seem to be symbolic links. Can you check if they are all physically downloaded (and accessible) in the specified directories? 
Note, these files are too large for github, and they need to be downloaded from this [url](http://www-personal.umich.edu/~xwen/download/).

**Comment by ruthchia** [comment]
Hi William, yes, all the files are physically downloaded and accessible (i.e. I can view the contents of the files).

**Comment by xqwen** [comment]
I would first replace the symbolic links with the real *.gz files, and run again. Also make sure the downloaded *.gz files are in compressed format (some downloader automatically decompress the files)

**Comment by ruthchia** [comment]
HI William, 
I redownloaded all the data files, and tried rerunning enloc.
I still get the same error message (see below). Thank you for taking time to help troubleshoot this - I really cant tell why it isn't working. Is there something that I have missed?
![image](https://user-images.githubusercontent.com/20730081/27641174-2619108c-5be9-11e7-88a3-27199f25ad99.png)

**Comment by xqwen** [comment]
The error message looks strange to me. Can you run the command 
```
zcat  /Users/chiarp/enloc/workspace/data/HDL.z_score.gz | head -10
```
and post the output (or potential error messages)?


If there is an error,  I suggest you re-download the ``HDL.z_score.gz`` file by issuing
```
wget http://www-personal.umich.edu/~xwen/download/gwas_hdl/HDL.z_score.gz
```
from the command line.

**Comment by ruthchia** [comment]
Hi William, 
I redownloaded the file using wget, and tried the command zcat, and  the same error appears. I did a little digging to find out why, and apparently, if using MacOS (which I am to run enloc), zcat appends .Z to the file.
Here's a link to what I am referring to: http://magnatecha.com/zcat-adds-z-in-mac-os/
So, i think that's the problem. I guess there will be a need to edit your code a little for this.
What are your thoughts?

**Comment by xqwen** [comment]
Hmm, that is an annoying feature of Mac :).  Thanks very much for the link. I will play with it on Mac, and hopefully, come up with a workaround.

**Comment by ruthchia** [comment]
Hi William, 
Thanks for looking into a workaround for Mac - I am sure it will be useful.

On another note, I have access to the HPC at my institution, and tried running enloc there - which I believe is on a linux platform. 
The initial error message is resolved, but now I am seeing another one having to do wth torus.
Here's the snapshot of the error message:

![image](https://user-images.githubusercontent.com/20730081/27739285-080b695c-5d7c-11e7-83f6-7b7219cd320f.png)

It looks like the -annot data file may not be correct i.e. there is a double backslash in defining the path of the file. 
Eg: -annot /gpfs/gsfs6/users/chiarp/enloc/workspace/HDL_blood/mi//HDL.annot.sim1.gz

would that be the root of the problem?( If so, perhaps a minor fix in the code will be necessary?)

Thanks!

**Comment by xqwen** [comment]
It is usually not a problem. But you could check the file by 
```zcat  /gpfs/gsfs6/users/chiarp/enloc/workspace/HDL_blood/mi//HDL.annot.sim1.gz | head -10```
If the output looks normal, would you mind emailing me the file ```HDL.annot.sim1.gz``` (xwen at umich.edu)?

Thanks very much,

William

**Comment by xqwen** [comment]
We finally resolve the issue that is originated from a faulty compiling of the source code. We will provide a static version of the executable binary for Linux in the repo.
